version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: staffing-process-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: staffing_process
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: staffing-process-keycloak
    command:
      - start-dev
      - --import-realm
      - --hostname-url=http://host.docker.internal:8081
      - --hostname-strict=false
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8081:8080
    volumes:
      - ./docker/oauth2-staffing-process-realm-export.json:/opt/keycloak/data/import/oauth2-staffing-process-realm-export.json
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/realms/master" ]
      interval: 10s
      timeout: 5s
      retries: 10

  staffingProcessService:
    build:
      context: .
      dockerfile: Dockerfile
    image: staffing-process
    container_name: staffing-process-service
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/staffing_process
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://host.docker.internal:8081/realms/oauth2-staffing-process-realm
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT_URI=http://localhost:8080/login/oauth2/code/keycloak
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://host.docker.internal:8081/realms/oauth2-staffing-process-realm/protocol/openid-connect/certs
      - KEYCLOAK_AUTH_SERVER_URL=http://host.docker.internal:8081/realms/oauth2-staffing-process-realm
      - KEYCLOAK_REALM=staffing
      - KEYCLOAK_RESOURCE=oauth2-staffing-process-client
      - KEYCLOAK_CREDENTIALS_SECRET=I3NGBPpQGNjBfuqIGt9CcoxhLY8pzydn
      - KEYCLOAK_PUBLIC_CLIENT=false
      - KEYCLOAK_ENABLE_CORS=true
      - KEYCLOAK_BEARER_ONLY=true
      - KEYCLOAK_SSL_REQUIRED=external
      - KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS=true

