spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            #            client-id: oauth2-staffing-process-client
            client-id: public-oauth2-staffing-process-client
            #            client-secret: gKh23Hm1ayeIu2oRsajttQR2r2i1Ou6E
            #            authorization-grant-type: password
            #            authorization-grant-type: client_credentials
            authorization-grant-type: authorization_code   #Login to KeyCloak redirect only occurs successfully on this(for public at least)
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            scope: openid, profile, roles
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/oauth2-staffing-process-realm